name: Daily Quran Video Bot

on:
  schedule:
    - cron: '0 2 * * *' # الساعة 5 صباحاً بتوقيت مصر
  workflow_dispatch: # للتشغيل اليدوي

# هذا هو السطر السحري الذي طلبته جيت هاب لإجبار التشغيل على Node 24 وإخفاء التحذير تماماً
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install moviepy==1.0.3 requests python-telegram-bot

    - name: Run Script
      env:
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python main.py
