name: Daily Quran Video Bot

on:
  schedule:
    - cron: '0 2 * * *'  # الساعة 2 صباحاً بتوقيت جرينتش = 5 صباحاً بتوقيت مصر
  workflow_dispatch:      # عشان تقدر تشغله يدوي برضه في أي وقت

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ... باقي الخطوات اللي عملناها قبل كدة (Checkout, Setup Python, Install FFmpeg)
